name: game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.0
  http: ^0.13.6
  shared_preferences: ^2.2.2

  firebase_core: ^3.15.1  # updated from 2.16.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.64.0
  url_launcher: ^6.1.10

  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/bronze.png
    - images/silver.png
    - images/gold.png
    - images/platinum.png
    - images/diamond.png
    - images/masters.png
    - images/A.png
    - assets/.env
    



