name: game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  provider: ^6.1.0
  http: ^1.4.0
  shared_preferences: ^2.2.2

  firebase_core: ^3.15.1  # updated from 2.16.0

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  fl_chart: ^1.0.0
  url_launcher: ^6.1.10

  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/bronze.png
    - images/silver.png
    - images/gold.png
    - images/platinum.png
    - images/diamond.png
    - images/master.png
    - images/A.png
    - assets/.env
    - images/TIER1.png
    - images/TIER2.png
    - images/TIER3.png
    
flutter_icons:
  android: true
  ios: true
  image_path: images/A Icon.png

