
const List<String> commonGymLifts = [
  // Chest
  'Bench Press',
  'Incline Bench Press',
  'Decline Bench Press',
  'Dumbbell Bench Press',
  'Chest Fly',
  'Cable Crossover',
  'Push-Up',
  'Machine Chest Press',
  'Incline Chest Fly',
  'Pec Deck Machine',

  // Back
  'Pull-Up',
  'Chin-Up',
  'Lat Pulldown',
  'Barbell Row',
  'Dumbbell Row',
  'Seated Cable Row',
  'T-Bar Row',
  'Face Pull',
  'Straight Arm Pulldown',
  'Inverted Row',

  // Legs
  'Squat',
  'Front Squat',
  'Goblet Squat',
  'Leg Press',
  'Bulgarian Split Squat',
  'Walking Lunge',
  'Step-Up',
  'Leg Extension',
  'Leg Curl',
  'Romanian Deadlift',

  // Glutes / Hips
  'Hip Thrust',
  'Glute Bridge',
  'Cable Kickback',
  'Sumo Squat',
  'Banded Lateral Walk',
  'Reverse Lunge',
  'Kettlebell Swing',
  'Single-Leg Glute Bridge',
  'Frog Pump',
  'Donkey Kick',

  // Shoulders
  'Overhead Press',
  'Dumbbell Shoulder Press',
  'Arnold Press',
  'Lateral Raise',
  'Front Raise',
  'Rear Delt Fly',
  'Upright Row',
  'Barbell Shoulder Press',
  'Cable Lateral Raise',
  'Face Pull',

  // Arms – Biceps
  'Barbell Curl',
  'Dumbbell Curl',
  'Hammer Curl',
  'Preacher Curl',
  'Concentration Curl',
  'Incline Dumbbell Curl',
  'Cable Curl',
  'EZ Bar Curl',
  'Zottman Curl',
  'Drag Curl',

  // Arms – Triceps
  'Triceps Pushdown',
  'Overhead Triceps Extension',
  'Skullcrusher',
  'Triceps Kickback',
  'Close-Grip Bench Press',
  'Dips',
  'One-Arm Cable Pushdown',
  'EZ Bar Overhead Extension',
  'Tate Press',
  'Rope Pushdown',

  // Core
  'Plank',
  'Side Plank',
  'Russian Twist',
  'Hanging Leg Raise',
  'Cable Woodchopper',
  'Sit-Up',
  'Crunch',
  'Bicycle Crunch',
  'Ab Rollout',
  'V-Up',

  // Functional / Full Body
  'Deadlift',
  'Sumo Deadlift',
  'Power Clean',
  'Push Press',
  'Snatch',
  'Kettlebell Clean',
  'Farmer’s Carry',
  'Burpee',
  'Medicine Ball Slam',
  'Battle Ropes',

  // Calves / Forearms / Misc
  'Standing Calf Raise',
  'Seated Calf Raise',
  'Tibialis Raise',
  'Wrist Curl',
  'Reverse Wrist Curl',
  'Shrug',
  'Trap Bar Deadlift',
  'Sled Push',
  'Box Jump',
  'Jump Rope',
];
